FROM netunicorn/chromium@sha256:20e4aee9b73a9502304f68c710ac483c6bf915f6bf0296d7300ea378f7912f42


RUN apt-get update && \
    apt-get install -y wget gnupg2 software-properties-common unzip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends \
    chromium \
    chromium-driver \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN apt-get update && apt-get install -y xvfb
RUN pip install google-cloud-storage


RUN ln -s /usr/bin/chromium /usr/local/bin/google-chrome && \
    ln -s /usr/bin/chromium-chromedriver /usr/local/bin/chromedriver

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


RUN mkdir -p ./extensions && \
    wget https://github.com/nectostr/pinot_minion_tasks/raw/collection/QoE_youtube/extensions/4.46.2_0.crx -P ./extensions && \
    wget https://github.com/nectostr/pinot_minion_tasks/releases/download/public/qoe_extension.zip -P ./extensions && \
    unzip ./extensions/qoe_extension.zip -d ./extensions/qoe_extension

ENV STATSFORNERDS_PATH=./extensions/qoe_extension
ENV ADBLOCK_PATH=./extensions/4.46.2_0.crx