FROM netunicorn/chromium:latest

RUN apt-get update && \
    apt-get install -y wget gnupg2 unzip

RUN wget -q -O chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chrome-linux64.zip && \
    unzip chrome-linux64.zip && \
    rm chrome-linux64.zip && \
    mv chrome-linux64 /opt/chrome/ && \
    ln -s /opt/chrome/chrome /usr/local/bin/google-chrome && \
    wget -q -O chromedriver-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.141/linux64/chromedriver-linux64.zip && \
    unzip -j chromedriver-linux64.zip chromedriver-linux64/chromedriver && \
    rm chromedriver-linux64.zip && \
    mv chromedriver /usr/local/bin/

RUN pip install --upgrade netunicorn-executor

RUN apt-get update && \
    apt-get install -y \
    tcpdump \
    python3-pip \
    uvicorn \
    xvfb \
    unzip \
    procps \
    curl && \
    pip3 install fastapi uvicorn uvloop selenium webdriver-manager Jinja2==3.0.1 cloudpickle==2.2.1


RUN wget https://github.com/nectostr/pinot_minion_tasks/raw/collection/QoE_youtube/extensions/4.46.2_0.crx -P ./extensions && \
    wget https://github.com/nectostr/pinot_minion_tasks/releases/download/public/qoe_extension.zip -P ./extensions && \
    unzip ./extensions/qoe_extension.zip -d ./extensions/qoe_extension

ENV STATSFORNERDS_PATH=./extensions/qoe_extension
ENV ADBLOCK_PATH=./extensions/4.46.2_0.crx

